language: r
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - drat

before_install:
  - tlmgr install fancyvrb units
  - sudo apt-get install -y libudunits2-dev libgit2-dev libgdal1-dev

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
